apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:4.4.6
          command:
            - mongos
            - "--configdb"
            - "configReplSet/configsrv-replicaset-0.configsrv-replicaset.default.svc.cluster.local:27017,configsrv-replicaset-1.configsrv-replicaset.default.svc.cluster.local:27017,configsrv-replicaset-2.configsrv-replicaset.default.svc.cluster.local:27017"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mongodb-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongos
  type: ClusterIP
